name: Commitlint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.tool_versions.outputs.nodejs }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Validate all commits from this PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
