name: Spec

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: tool_versions

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.tool_versions.outputs.nodejs }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Report Test Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.github_token }}
